module.exports = {
  'Create New Property' : function (browser) {
    browser

      .url('https://cedev.channelauction.com')
      .waitForElementVisible('body', 1000)
      .setValue('input[ng-model="loginCtrl.logonName"]', 'jose')
      .setValue('input[ng-model="loginCtrl.password"]', 'jose')
      .click('button[data-elm-id="btnLogin"]')
      .pause(3000)
      .assert.urlEquals('https://cedev.channelauction.com/#/app/cas/dashboard')
      .url('https://cedev.channelauction.com/#/app/cas/property-file/new')
      .pause(3000)
	  .waitForElementVisible('select[data-elm-id="productType"]', 7000)
      .click('select.form-control option[value="string:traditionalListing"]')
      .waitForElementVisible('option[value="string:976a9c91-4a1b-4edd-b259-224129bde27e"]', 7000)
      .click('select.form-control option[value="string:976a9c91-4a1b-4edd-b259-224129bde27e"]')
      .pause(3000)
      .setValue('input[ng-model="model.propertyAddress.line1"]','1219 E 81st St')
      .pause(1000)
      .setValue('input[ng-model="model.propertyAddress.zipCode"]','90001')
      //Property Details
      .waitForElementVisible('select[data-elm-id="propertyType"]', 7000)
      .click('select.form-control option[value="string:Single Family-Attached"]')
      .waitForElementVisible('input[data-elm-id="yearBuilt"]', 10000)
      .setValue('input[data-elm-id="yearBuilt"]', '2002')
      .waitForElementVisible('select[data-elm-id="homeStyle"]', 7000)
      .click('select.form-control option[value="string:Colonial"]')
      .waitForElementVisible('input[data-elm-id="storiesNum"]', 10000)
      .setValue('input[data-elm-id="storiesNum"]', '5')
      .waitForElementVisible('input[data-elm-id="sqft"]', 10000)
      .setValue('input[data-elm-id="sqft"]', '1500')
      .waitForElementVisible('select[data-elm-id="garageType"]', 7000)
      .click('select.form-control option[value="string:Attached"]')
      .waitForElementVisible('input[data-elm-id="garageNumCars"]', 10000)
      .setValue('input[data-elm-id="garageNumCars"]', '2')
      .waitForElementVisible('input[data-elm-id="oneQuarterBathrooms"]', 10000)
      .setValue('input[data-elm-id="oneQuarterBathrooms"]', '1')
      .waitForElementVisible('input[data-elm-id="halfBathrooms"]', 10000)
      .setValue('input[data-elm-id="halfBathrooms"]', '3')
      .waitForElementVisible('input[data-elm-id="threeQuarterBathrooms"]', 10000)
      .setValue('input[data-elm-id="threeQuarterBathrooms"]', '2')
      .waitForElementVisible('input[data-elm-id="fullBathrooms"]', 10000)
      .setValue('input[data-elm-id="fullBathrooms"]', '1')
      .waitForElementVisible('input[data-elm-id="totalBathrooms"]', 10000)
      .setValue('input[data-elm-id="totalBathrooms"]', '3')
      .waitForElementVisible('input[data-elm-id="bedrooms"]', 10000)
      .setValue('input[data-elm-id="bedrooms"]', '8')
      .waitForElementVisible('input[data-elm-id="lotSizeAcres"]', 10000)
      .setValue('input[data-elm-id="lotSizeAcres"]', '4008')
      .waitForElementVisible('input[data-elm-id="lotSizeSqft"]', 10000)
      .setValue('input[data-elm-id="lotSizeSqft"]', '5400')
      .waitForElementVisible('select[data-elm-id="landFeeLease"]', 7000)
      .click('select.form-control option[value="string:Fee"]')
      .waitForElementVisible('button[data-elm-id="btnCreate"]', 7000)
      .pause(5000)
      .click('button[data-elm-id="btnCreate"]')
    .end();

	}
}